// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmkY2ykZos_EyObgJ7Z6LmNnaDMdikxzs',
    appId: '1:210169955461:web:be7ea0b1a3eb924c3b95ec',
    messagingSenderId: '210169955461',
    projectId: 'content-vault-4bbff',
    authDomain: 'content-vault-4bbff.firebaseapp.com',
    storageBucket: 'content-vault-4bbff.firebasestorage.app',
    measurementId: 'G-4DXLQX8VCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkCAPOPgIQ7yesHD0SHhoXrQStlKBhl6s',
    appId: '1:210169955461:android:84ae60bed3ead8433b95ec',
    messagingSenderId: '210169955461',
    projectId: 'content-vault-4bbff',
    storageBucket: 'content-vault-4bbff.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3TXkn1eagFWgloItA3_Gz6eAGqQNN8AM',
    appId: '1:210169955461:ios:a61f1ba46805b4213b95ec',
    messagingSenderId: '210169955461',
    projectId: 'content-vault-4bbff',
    storageBucket: 'content-vault-4bbff.firebasestorage.app',
    iosBundleId: 'com.example.contentVault',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3TXkn1eagFWgloItA3_Gz6eAGqQNN8AM',
    appId: '1:210169955461:ios:a61f1ba46805b4213b95ec',
    messagingSenderId: '210169955461',
    projectId: 'content-vault-4bbff',
    storageBucket: 'content-vault-4bbff.firebasestorage.app',
    iosBundleId: 'com.example.contentVault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmkY2ykZos_EyObgJ7Z6LmNnaDMdikxzs',
    appId: '1:210169955461:web:5a5e6494e53e27913b95ec',
    messagingSenderId: '210169955461',
    projectId: 'content-vault-4bbff',
    authDomain: 'content-vault-4bbff.firebaseapp.com',
    storageBucket: 'content-vault-4bbff.firebasestorage.app',
    measurementId: 'G-EVZT3MJCH2',
  );
}
